name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag inventory:$(date +%s)
      
    - uses: itsvinayak/pylint-and-format@v1.1
      with:
        filename: 
      
    - uses: Somfic/cleanupcode-action@1.1.1
      with:
        solution:

    - uses: authzed/action-testserver@v3
      with:
        version:

    - uses: suitedaces/ai-pull-request-reviewer@alpha
      with:
        # GitHub Token for authentication
        GITHUB_TOKEN: 
        # OpenAI API Key for accessing AI models
        OPENAI_API_KEY: 
        # The OpenAI model to use for code review
        OPENAI_API_MODEL: # optional, default is gpt-4-0314

    - name: Code coverage-reporter
      uses: tj-actions/coverage-reporter@v5
      with:
       token: # default is ${{ github.token }}
       # Specify a coverage command to run the test.
       coverage-command: 
