name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag inventory:$(date +%s)

    - uses: creyD/prettier_action@31355f8eef017f8aeba2e0bc09d8502b13dbbad1
      with: 
        commit_message: # optional, default is Prettified Code!
        commit_description: # optional, default is 
        # Update the current commit instead of creating a new one
        same_commit: # optional
        # Commit options
        commit_options: # optional
        # Git push options
        push_options: # optional
        # File pattern used for `git add`, can't be used with only_changed!
        file_pattern: # optional, default is *
        # Options for the `prettier` command
        prettier_options: # optional, default is --write **/*.js
        # Running the script in dry mode just shows whether there are files that should be prettified or not
        dry: # optional
        # Specific version of prettier (by default just use the latest version)
        prettier_version: # optional
        # Specify a directory to cd into before installing prettier and running it
        working_directory: # optional
        # Only prettify files changed in the last commit, can't be used with file_pattern!
        only_changed: # optional
        # Install Prettier plugins, i.e. `@prettier/plugin-php @prettier/plugin-other`
        prettier_plugins: # optional, default is 
        # GitHub Token or PAT token used to authenticate against a repository
        github_token: # optional, default is ${{ github.token }}
        # Remove the node_modules folder before committing changes
        clean_node_folder: # optional, default is true
        
    - uses: itsvinayak/pylint-and-format@v1.1
      with:
        filename: 

    - uses: DataDog/datadog-static-analyzer-github-action@v1.0.7
      with:
        dd_api_key: # default is 
        # Your Datadog Application key used to authenticate requests.
        dd_app_key: # default is 
        # The service you want your results tagged with.
        dd_service: # default is 
        # The environment you want your results tagged with.
        dd_env: # optional, default is none
        # The Datadog site. For example, users in the EU may want to set datadoghq.eu.
        dd_site: # optional, default is datadoghq.com
        # Set the number of CPUs used to by the analyzer.
        cpu_count: # optional, default is 2
        # Get the execution time statistics for analyzed files.
        enable_performance_statistics: # optional, default is false
        # Lets the analyzer print additional logs useful for debugging.
        debug: # optional, default is no
        # The subdirectory path the analysis should be limited to.
        subdirectory: # optional, default is 

    - uses: Somfic/cleanupcode-action@1.1.1
      with:
        solution:

    - uses: authzed/action-testserver@v3
      with:
        version:

    - uses: suitedaces/ai-pull-request-reviewer@alpha
      with:
        # GitHub Token for authentication
        GITHUB_TOKEN: 
        # OpenAI API Key for accessing AI models
        OPENAI_API_KEY: 
        # The OpenAI model to use for code review
        OPENAI_API_MODEL: # optional, default is gpt-4-0314
